# Generated by Django 3.0.5 on 2020-04-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=3)),
                ('age', models.PositiveSmallIntegerField()),
                ('fur_color', models.CharField(max_length=20)),
                ('body_size', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.Breed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
