# Generated by Django 3.0.5 on 2020-04-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_auto_20200422_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
