# Generated by Django 3.0.5 on 2020-04-27 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20200424_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('shelter', '收容所'), ('abandoner', '送養人'), ('owner', '飼主'), ('volunteer', '善心人士'), ('finder', '發現者'), ('other', '其他')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('shelter', '收容所'), ('abandoned', '主人送養'), ('lost', '走失訊息'), ('stray', '流浪動物')], max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', '可領養'), ('sent', '已領養'), ('dead', '已過世'), ('complete', '已結案'), ('unknown', '未知')], max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Animal')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
